{pkgs, lib, ...}: let
  theme = import ../../../themes/axterm.nix;
in {
  programs.fish = {
    enable = true;
    interactiveShellInit = ''
      ${pkgs.nix-your-shell}/bin/nix-your-shell fish | source
    '';
  };

  xdg.configFile."fish/conf.d/prompt.fish".source = ../../../../config/fish/conf.d/prompt.fish;
  xdg.configFile."fish/functions".source = ../../../../config/fish/functions;

  # Generate Fish Theme
  xdg.configFile."fish/themes/axterm.theme".text = ''
    # axterm Fish theme (Generated by Nix)
    fish_color_normal ${lib.removePrefix "#" theme.foreground}
    fish_color_command ${lib.removePrefix "#" (builtins.elemAt theme.palette 4)}
    fish_color_keyword ${lib.removePrefix "#" (builtins.elemAt theme.palette 5)}
    fish_color_quote ${lib.removePrefix "#" (builtins.elemAt theme.palette 2)}
    fish_color_redirection ${lib.removePrefix "#" (builtins.elemAt theme.palette 9)}
    fish_color_end ${lib.removePrefix "#" (builtins.elemAt theme.palette 7)}
    fish_color_error ${lib.removePrefix "#" (builtins.elemAt theme.palette 1)}
    fish_color_param ${lib.removePrefix "#" (builtins.elemAt theme.palette 6)}
    fish_color_comment ${lib.removePrefix "#" (builtins.elemAt theme.palette 8)}
    fish_color_selection --background=${lib.removePrefix "#" theme.selection-background}
    fish_color_search_match --background=${lib.removePrefix "#" theme.selection-background}
    fish_color_operator ${lib.removePrefix "#" (builtins.elemAt theme.palette 3)}
    fish_color_escape ${lib.removePrefix "#" (builtins.elemAt theme.palette 14)}
    fish_color_autosuggestion ${lib.removePrefix "#" (builtins.elemAt theme.palette 8)}
    fish_color_cancel ${lib.removePrefix "#" (builtins.elemAt theme.palette 9)}
    fish_color_cwd ${lib.removePrefix "#" (builtins.elemAt theme.palette 2)}
    fish_color_user ${lib.removePrefix "#" (builtins.elemAt theme.palette 6)}
    fish_color_host ${lib.removePrefix "#" (builtins.elemAt theme.palette 4)}
    fish_color_host_remote ${lib.removePrefix "#" (builtins.elemAt theme.palette 3)}
    fish_color_status ${lib.removePrefix "#" (builtins.elemAt theme.palette 1)}
    fish_pager_color_progress ${lib.removePrefix "#" (builtins.elemAt theme.palette 15)}
    fish_pager_color_prefix ${lib.removePrefix "#" (builtins.elemAt theme.palette 4)}
    fish_pager_color_completion ${lib.removePrefix "#" theme.foreground}
    fish_pager_color_description ${lib.removePrefix "#" (builtins.elemAt theme.palette 8)}
  '';

  # Apply Theme (Syntax Highlighting Only)
  xdg.configFile."fish/conf.d/theme.fish".text = ''
    if status is-interactive
        if test -f ~/.config/fish/themes/axterm.theme
            source ~/.config/fish/themes/axterm.theme
        end
    end
  '';

  home.packages = [pkgs.nix-your-shell];
}
