# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd = {
    availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci"];
    kernelModules = [];
    luks.devices."crypted".device = "/dev/disk/by-uuid/16aee600-e470-4a2b-8553-29494b8295b8";
  };

  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/26e0f1cd-0d9b-4c8c-8c2a-e654cc3c5de2";
    fsType = "btrfs";
    options = ["subvol=@root"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = ["umask=0177"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/26e0f1cd-0d9b-4c8c-8c2a-e654cc3c5de2";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/26e0f1cd-0d9b-4c8c-8c2a-e654cc3c5de2";
    fsType = "btrfs";
    options = ["subvol=@nix"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/26e0f1cd-0d9b-4c8c-8c2a-e654cc3c5de2";
    fsType = "btrfs";
    options = ["subvol=@log"];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/26e0f1cd-0d9b-4c8c-8c2a-e654cc3c5de2";
    fsType = "btrfs";
    options = ["subvol=@cache"];
  };

  fileSystems."/var/lib/containers" = {
    device = "/dev/disk/by-uuid/26e0f1cd-0d9b-4c8c-8c2a-e654cc3c5de2";
    fsType = "btrfs";
    options = ["subvol=@containers"];
  };

  fileSystems."/var/lib/libvirt/images" = {
    device = "/dev/disk/by-uuid/26e0f1cd-0d9b-4c8c-8c2a-e654cc3c5de2";
    fsType = "btrfs";
    options = ["subvol=@vms"];
  };

  swapDevices = [];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
